apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev

resources:
  - ../../base
  - namespace.yaml

patches:
  - path: patch-ingress-classes.yaml
  - path: patch-images.yaml
