# NOTE:  is replaced by the Deploy workflow.
# Default to "7dd8dfed4b0e6ce3f60d8cd7fe1496b397e6bf15-dev"; workflow can pin to "${SHA}-dev".
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  template:
    spec:
      containers:
        - name: backend
          image: /backend:7dd8dfed4b0e6ce3f60d8cd7fe1496b397e6bf15-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  template:
    spec:
      containers:
        - name: frontend
          image: /frontend:7dd8dfed4b0e6ce3f60d8cd7fe1496b397e6bf15-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: callmebot-adapter
spec:
  template:
    spec:
      containers:
        - name: adapter
          image: /callmebot-adapter:7dd8dfed4b0e6ce3f60d8cd7fe1496b397e6bf15-dev
