apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  template:
    spec:
      containers:
        - name: backend
          image: __ACR_FQDN__/backend:latest-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  template:
    spec:
      containers:
        - name: frontend
          image: __ACR_FQDN__/frontend:latest-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: callmebot-adapter
spec:
  template:
    spec:
      containers:
        - name: callmebot-adapter
          image: __ACR_FQDN__/callmebot-adapter:latest-dev
