
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ibrahim3321/the-last-projects-
    targetRevision: feature/ci-cd
    path: aks-yaml/secrets/dev
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  revisionHistoryLimit: 2
