# NOTE: __ACR_FQDN__ is replaced by the Deploy workflow.
# Default to "latest-prod"; workflow can pin to "${SHA}-prod".
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  template:
    spec:
      containers:
        - name: backend
          image: __ACR_FQDN__/backend:latest-prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  template:
    spec:
      containers:
        - name: frontend
          image: __ACR_FQDN__/frontend:latest-prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: callmebot-adapter
spec:
  template:
    spec:
      containers:
        - name: adapter
          image: __ACR_FQDN__/callmebot-adapter:latest-prod
