---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBBGzCEWm4Rj/b3Qah/ioBACgKZYs3Hl+Sl9b0vBJ+dkzUjpRJcurhJQgoJoYQmUO1zMtP6WYvwC3bx8XMQAWD+qLlAoLQ4j+PdCMgA+DxhoFY6Knhrjw3oi4IBhopiHWaYVzNis4IQYHuMoTPnxNsvGk6FQn/uhA3chmM7MclFmxIrpeLNw2Nkw5xdNd844V8sayJ09r1qMPl1J5A40G+W/1Bqi1dbxEChMsEEel6zzN+jTEZmgzMdbiBQ/hTcpL/hrdF+8/OVgFALl1to9WoFI/E6NFLAlU5Y7TMWYQwCuCUYBITLq7euSmZMj986ovjkbvD2mnb0tM6lVXUFicF0N7+yEts9yLaL6IIJXyQZATJdarQrKfWOB9knVHh5gvDdhJLxTcMBGsRfrVQ2qQMmfDgt5kSPbl1gyUpQ1i7HrftPhDy+QXJjvKbptl0WIsUKkYPhmHAbs862PWgldN0Lq7BRdgY0sMEksV50GgY56vvo3S6ZiKmJA4gsJtzXIAk0vLXynkR0rDALJvBHvLCM7k+4cRELfaSQb6W7W/9iZ0UxxMm9cZ5p8+XiYpxdh57cgF9xtX88kMdEUkg6KgmoaHWO5J32DqMD13ePX09duTLiL5KV5Oquv+UIcJiRPReGfjC9VltiLP/OZN6lTWyRrBDLz03zibLTIijNNoeym5XlMQXftaK9Th9aa5lY0W6Rv7DQBEd34eN792VzWCfYHA==
    admin-user: AgDqVuhpFS0AG8KxiN2pImd2t7+bAUDJfv5WbOFr8wzDKukXEfyFlxZMfDFyfmwgH0TrMoUVwWmr1DdgWjmrLKzTymd6jK5Dn3ZDQE9dmS/2vIwKl7pBQalqSq5VXCwMfWeVx8S9vuUX+Ob5u7uxbNMWg4TpvS0hlEuqUOQpoKJ9lWqTcPk7agpRdG9IBYzQ4bs+DMf11fkhjjsqWvPEr28Qri/3SwhHyBj9C7CamgsFZdLSVyahFAapV+0qM+maA98qn0SQVkWyR8/gEaDudxQVbPsjsKCF1xhP9NXeM0cZZlqIVsKQDG35B7vJ/rgQYolEfwTg88rLyYywLax8efSd8wZlSbQZRbcdyAjAqCUX00VHv4PfySJeFgEWY3kfwzMVeTFHjuHfUZ1r6fbqreFUkW+5bJh68qCbsuJvUOabVvm17NaZ85qlWWmetENjJOFpFakLKfX1uQEDQG6xIasJrlclIyLRvjwjl1HVFWz2U5IdqbFfEb1EUDkyC2ZgPcMbwuYgxrLSowAJW14RBv8q4zSZAknDPjr8FMt3792UgpE71iOHaWzsg/aOKshvsWDZzJOgcm7j2eVzbxFboI+Mq7rEV1YLuidJ2mFb1+rlOj5TVXTefoPRVsJgNpfrO9Yb228q0TTBGhyGjZIvm2HFGGbsmZHoLUYXBUF44Tcw66T6hcwZns6gsfQ2fNPDURJlOSGlOQk=
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
    type: Opaque
