---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slack-webhook-url
  namespace: monitoring
spec:
  encryptedData:
    url: AgCQcUflHjU34sISbHEgj9tJNRhn0CSyZEwujIiTLQaUGkv9AOdeD5o4siiCLl06cYXX41tCYns5ubUXxxx/A2vtyCJtIAwLAPkWCtS78EsdRfBz5HGrSrzO5N7eZraP1XpCnto7sJ+L6/9OZOCV7MRe7VqcSDEkh3LbOZ5YtZhMVlY/ch5ZHhPg67+2VMTuul7wPCuLg7CP1IlruejKgt5gqk937Wl24wNB+U7vRf8gOwAVcvOQMu1HIFkUOozSLU5gYXlYJXT+fM69WJcJrDXlVuG7OF1nrOqjx6nUnnw4lwQ8yTcsIPX00Msid1L6p8UNoPwMZyTpIR3beS1XazVpybznZApwU64ZtAmlQPa9h5Rt6BydmF6sCIpsLreW6aFyl8xAxLnCQrK2N39kZXi+PJyZKNRMx673gE/d9l57HagnotWovYiP1jtxrGMucnFNGAOCykRPGSQjTS7wrFhGlkrYTo5y41ORcsEYfvaSfgSbrzDyH8V9D6ncK+U/kkcVsokqEdDmDqfEzU9A0YT4DiOBCTRiwwXyx+NxnG13rxp0GtYzASXOiZHnL9kwjZtyuASW5hJMIY603vZs1RaKttPRxchiGAG3cyhcEsntKUb8mz9VF45/hgub8aCgcRFFIF9ACsSf99JTiHMfK5vT122xff/7FJBxrewtw+aNfXj7uLxDHV2Ykl1LEbqCxIBfijIaBuyuvnX6OuB5ILKs+ThGbhMn6maVrcoqNzZ3nzkH72c0ah6KplZxkFsjHvhF1pqCeJe9onwQ6Paa6t9VPdKW0w4gYsyzB6Wf/tt/CfUm
  template:
    metadata:
      name: slack-webhook-url
      namespace: monitoring
    type: Opaque
