---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    GRAFANA_ADMIN_PASSWORD: AgAF5nBMdcSQWEoJKQJUQXYPrX6T0/tNv1JRV7YWbxL83sdDEiZCZQpkTvPgWQNKaV2txFxxMldugi2q0GUNSfzMv3cp8fLiHE64FHhlY8z5RjB0nvmtzej5ZPgCR7pxEZ0PIu06nOU2eIOlcTVd68m28Xp2FE1DEs4RFunCDxL/263pdOM7JylPEQQblGyJbcKdGE4j/Nwxmk0jNdA0E82f/T7MtUCWWdoB6XAPVUg2Pp/5UVeqKqrZjuoir12dAVowW4PvztgagEWlKG2/929MZj/LZroJGdbhr9ilig5XnRiwB+z6Tt+cWWZij1Q9jTlfx0Jud41V1qXK9iFuifFmovJIV5cqR54Ytw+QxQ6LmOIhzRRT/NhQs48pee/3AMk1h0lp8HESYGmN7QMqQJV5ZH+gt/c8slCFKfjphyM9/k7w4/vILscKYf1sbBkR6XbD5+sB+pOZOKVWoEx4h4n2WBCWdUTkh87otLVPG6v4n5K9zIW1qyDI5FDRQnJmDwggo4+D5b0g8DEJWFdGALs9DT/EaI3c1NyGCr+dk3eO1T/LZW2RPzG/QKoeUG/MwEhpQ0lKUSDqYTE9iJ7x0ofhFWEeWrtEID/gbXXHlXWj/7dx5HvdkWfv9qJVjlFTN8+9W4373iu7X4/9YMOkRJXHNdrGhBoplWnj1W7JtuiSUerWyPdQ4fKfHiz706JBdqxHJ22ULEIJ6q8VBZhcf9kNUQ==
    GRAFANA_ADMIN_USER: AgAIxMROIEmzs2hvYN0ggLG4qtqZ5MMCWC/ykbwZoUcyKqWbKm330zuNfOXkgcZTyttZ7bxHbSMdlZpMAYRorNJE+GWznuRxrCaZI90dgCGYSX7gc/NAkHgGONX/qCzkgTvSqSfsBGSkgRHq6I2B/XP6q6f4jmcKdQeunon/sIUpQ6CcFv4lia8wQUpKz46j1MAs4FWbj6kboZwxY12WXac+4O9YmOSPyowvV0EIFl8S3GM90yoRIwskjdJ/RtG+j9wUcfFDLTSe/cOn+Vw+5w5qdfMqxznmTpecYSS+TGcLlYhonHuqR9K6GG57TOl8uavMsb9b9RpCK97L0VL7/+gI0tgJglR2ql6O9SJ0ccIEeZ5zOAfOGJU7j3aXWHygrrtEt8MYR98+I1e3qtBvSlGi2QzZOD3+M10Ictdp0B1hBgcm5rN6e9k6iNaAspeuuHIzW2jvfl4qQH4CDefocn8coktDLN2IUniCnRD4Rq6ZDw6cQgBTe/U5prT5R9dHNp7Gc10kVEjLiN9HVYyDidLzqmleMInc1pF+Gyzkzq+BvipL1ob96F0OoN6nI01i8h9ANdD5ZcDPoBtEE1sDcz5avqHwTT5qNwJm+ND1M1W5gwUwYSlWUHkPfziXFOqqwcp1ZQCkeZnYYYwXlpvepBxTesQHW1hC5fsYJgDSlrzwD/R21KuoXBJrk3Q9cr1XgS1QtduN2Co=
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
    type: Opaque
