---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    GRAFANA_ADMIN_PASSWORD: AgAQeqgKecT9+UvH4amDeeH3K+PvhLTQoYV7WWhp3T465VL/SYxhjAYL5n78XVVNeZkndgjSmTqr2cV5+Y6CXZyeT0h5edFZDI0tfh+wQe3aRIjPkXNFF1wEsp/tBLKQcG2HIKnlZFnft7T4Rg5ar4H0dst/SR4jCNVmQEqJXEoCpcTl9I4coSmJrgxiuMBePitPUllcd2UBapBf5K7aJs/P4RSbRBwAs/+mGORah8vB0QYDdrAm/C27DSi+ZgyouxhdnBLe1/KW0HvKEwD7WWc8rDQAjj/ajmWWf06gJgz4j/GAFe2njzSE68zxfDSNLKxQhJcAUFnlqAJVE+gRpz+bzhvQIACKJxcmJ6jL7n139T/xGUPUJ2OkNIZqWm1HLcgdlH7rzXAuUF6ikv2FNHyJ1pelqI9xvZaDM0C5YpC5kSR0hxwvw+Qgpz0N3SVCdCf/2ZrsBbEJ2uaNFyE7JiI2fB+qp/KmbiuIse2/Rk6Tn3hjeCbAmZjLFqQ3wUYUyiYiKdqDt+Qti45QOsa6k9++Hg6A0WE5FP917oJm4eitl5GhMubXR1NJKlTU9H9PfxzHp37dlOBncuk0+qbgLJjEnPnH4VGuiSDAqRnjtx45C5mdIaHz3JtpSkcuc6leBSWdHIzGDbFOCfIsisWFBUrElxtskgO1BLMRuQw25QSULzE9fwrJgg/rnOrMoKPqnMJUo5F4MePkHITjfdMdrqHELA==
    GRAFANA_ADMIN_USER: AgA7L0Kwpk2z1Dr6+9sV0UnxEirDuG2eFi+bppnIcn0zUh6sO2PlQhZc+EoF+fI2ON+OXgaGwuIAkA/iDry8NJUfBJbpNROI6DuLrQlQYZnQOVrOMlTAWBaal8hGFZIFD0tW9IFk3M5LZK5Yr8BvPVS9PgWirJagXXsMtM2D7hj2gFGRj/vWwwXF6yIRss3DOM22zFPdgHsCbX1hLGu8Kz3CP6BmLN0YNDEg3R13424pptiyRbbrkntsp15gnhJKfUxC7C+eQmAuX36/PnD1oZar4r2XNF4z4STlWckxMdk/Rasx1NW9Jpyrcq9xgODqpMswu2VD0sONLnuRp/9Qwhg8kYyHz5bbrJKrX2QrferrVsfvrVbT1yrLMy0iW7Ap7PO72FJM7gr2cCkvNtldUhQpk/NfmWr0QtFhOs/Jp3mnmCklQUPS5CbI4XEeD5xJ+7xy/me/hI8wbQdvHtnK/QXXZdCbtZWw08lFFetTwondUHNWE5iERuIL2u/OJd/1WDcUfbdqONaj9J9W+lVFF7f+9/8LJeb1Jzx3QJJhqVrcd1zAPj1g0DsfnbwePFiZZYKLgR2jH4xDe/NVYY8PM+qDn2WLxagwADgWQGywfWbQBdf6C9ocVeNaLijq/MSOLLYWMRwUkFl9p+c4JNLNogwJoYVTWf/oBBuoUNbLwKI2i47LxlKfRi2SUTQ8uWsoEIJLElQYZgw=
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
    type: Opaque
