---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    GRAFANA_ADMIN_PASSWORD: AgAftGS4fxYZ2YtUEVLAaGioqnCceLeGndbzTd/cOeYJcFVQf4/S0Sx+4AWBuAHLP0nz08gVj8IWTABTNNgiRBneGLCMEF13k5NNARfm5VN0VoC2KnukyQO62gAioGk1tZuukUmAqIhLqAc8zZVoCVZ3LhI/CxgtXZPeMEdOscLULZZQuRXpGK1lNH0BzS1NEzarJuA0g7gV/HI+C4OPp/EZ8JzLTnrzQ+pci6dY4TwFfJpTe3C3q5R0y/LjdyokT7jBNolKm3l/BEbMx2VyUHs5L2Jl08OgCcZ+Jo8VpvpZCJdzZZ28wZDX+C3PPPe9e1m5LL2YNZYQDYWWpcS3Xsb0hVUznWCZjNFDBJhkPjFj4bOFRvL+Uk3qKBaEWsk1Ete6WAU7SneHMyuz7tbq/FKgbP1bPwUkkXf9dKCZUsWU3MlwEr5YYzG204WL9FxWF7WvDhiDwhChQKExhQyk0RrilrVAoh3y6SfVVfio6ZEWPEZGm0O3jZIzW8T2r2g9S0vFzLs75179AWw69ehnCkV4hb8YHczo6/8q2R5FfetI2M9lc0b0QohraN4XlDfCtF/N4rHJPilWAI6PmTbMgRcFQJKzdnZC8HMnIgrt34e9pBzdNDA89rkcyFJsvduQ6/GWr04RWan7ryElIGmWnoqaACr9qTWfMfxfeZ3K3xtshVcXXU7Oj//AggPiG3+96f5Busqk0tUWlPcXE4TrFsokQw==
    GRAFANA_ADMIN_USER: AgCrhCER82+8AVGBV/Qb5wtqjhcTe2JR14jOLoYnHqPVVRliKVwaxZsmf70INYKJOtZrnHClV8BGD4+5ME+2R3zQ6x6WMLOY1qDdgfAt2y8RcypATgJom+zhs/xcokMFAkZyBc3317QBSHffOUh7iV1MwVYvRCtHdJDTCbK6cmFts3YQxyH83L/oB8vvDqizx24qL3t7SBf4OD28W1mNCSDLPB3Lz+wu2CsYTamuZq1lFFye84iYJmhZ5oJXgQ9gq1hYI7j4vefLGF0BwJhtlJeEONdZeuGRLywym4sMCQleaJgXKZj6KXqbRARqI3lQBgycrAuaVFJWBARq3mPD/q8Dk/XmGl/u76E387koUD/Wow6vux3YOJmELV3hxPSi2jJ9h+iVApGtliTqNRFa4UuWJ0uDo/hR5IDyYSeHsBcguu7E73P0dRGFG/IWE2+/WXg42Tc+6mjEy3Pcg7JuYdvIGnyFRIYvpw9/9/yxLIuQmb4vXunj7i87khnFNahMFshWs32D9XstetN1PAspahTon5x0tTGs+37M+elA6AxSuwjTEhsrgXBeJFOJCkMMgluqe4uL4FdeCTmrJ2X+MI4jCztdl7nKonrAL5nor583ZDg86AAmXNqTP955Jz7mbgTpO/FEc+qRtMqfsR3XW/GvXDJ5Oz4NhhQ44ArXutXEbrWRnBlbokYdFU3RBvTzzrLazY4NjDM=
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
    type: Opaque
