---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    GRAFANA_ADMIN_PASSWORD: AgCjGyIFF/2FOvX7H9EjUMxMkGjTQXTJ/vyXgGMpQP/ZEyrh1bn/nJFl28Uw9IXUYEwZtgG1ySXeuNXIs3HW7cC0PQ9Kvd+KJh1KlMfTKR37/SQgmutlqKeN+DnGOoa497hV5aXOvjcxL52SAvRpWEBI7Tmv/TJDxkHPWViY8JnwlNNCcL2sPjCZSHcUKHNStN1SaBps3evNmFN9delE9+3lEkoFoLJBlQA1tfvgb9XSkFcu42exJg/XGY4EmC83v/P1hhEd5Dbb5AurtUrhKEVLJ51Dr8t0ibFKIB1G0t1xDfS8Q6gdlMpqyp3amkAOI+L8GLuFZ0oYk21wRc6fQ+H73OBj7SS92qksPumV4AhVGVPM+fYmnVeU0/Sxqb9oetYdYWYV57caXlO8cM7wREDNm8MF+JaYGpO8eQdSfROO3aAOZZOwmdP8imrm7BHIAgEWxKX349x2HPqmMqY7+xdE1tnHG/BEb9y1i5enl41f78XAsl4QoUYe5zC3+Hao3Ltgef1pnKMnHlCGK8dhpDtDqJcVTYpDkzayG/cNBvZ99sgl2JHK4U7XXIB51JYDDTc2tcU+9DAVhi89r3RufCsL9YT+qj8cYUVc8lO0NXfob4aP1zr0m7LSKn64mTxT00vhubh3Zyp688tcbG14EpW102c1UwWFb9cG0IFyZoOmpKC4+vhqbfWDKuRHzaWxyyduzz8CCBZrYM0zzelVDH7mZw==
    GRAFANA_ADMIN_USER: AgCH2Q+PoN+r0P1fLsCabbtMxyAJ21IDfhevFveLz8juoUd0UIS4vmjFBozJhnpPHTVNabmVTvjABG5eC3aDdlB5Ra0HinIiqnnhixXNgTV49ob/gxKb+J7yyMNajwIUHTqgPFc8gSboRTdZoBUNagg/RbrCJdK+B819miRKFX+m9o2jr4qn/m/aBGfwVI+kW30tu+HxyMB+VUDJaNiO+Wq7NghorRJeDvw3l3mQtoggLkyjim1wHC+w1BGOxpw98hwATIO0tGbfoGq+zVo75BjBUl+VWXh5VBLlSjWEQd3h0uN0p1PSG2i3jiYCvdGJsuZcs3JWJL9ePRjMin+IdvtUjLUfcpblNKsWAE7bm76J5zlt1Y4yZnTsyQX+CMK3zWBGCX5jFzmeZVX2zIbzS+3OdfczfOwasGC4kIQFgpH5JisC7y4vz2+jm70y1IsgUnTK7iYmZZUvca/V8n4wb2xcvkxSqa2PCxm7Ksa8S9LvnRJUov6lPjBC918gHG74Tm1do00jpoCxuxmi8m0gM4Qz24kg9ytHLhXFhFTWsP9M3Eq8tDmBk0niCeH4aGrPNNCCi8pptPwuCTm6JWCwuAWJoDJ9qhqndCH9JB41gmEBR/9GKUuCDEQv9mxqVXwlcCzlsf97uw/eKR79plVRB4qp6IE6U+PJJpD0lB4xa5A/ecR4wcT0h5IVIMHB8vruuNsKmlvdOSY=
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
    type: Opaque
