---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    GRAFANA_ADMIN_PASSWORD: AgChiImjVO1imidpCxBuxYGBun7y3XYu0rKGCDEjrpvoO4uccH2bPyhKMKbpFiO4Z5rBUs68e+yUZXQ7+EnfnKIiDBYMtMRXyEyEezh5NlxvurCiBHmV0bhuumtxo2ibkjUf2CaVRhwxE+v92FAo77yor/ChCK3zfrepcgiZeSMz474YSsa91sDd5SPWTceen4gy8QScM75IAr7HijYJgPAABbQYoYVPf6sC2giPX3AqZ4ghNRZUdyMYYSOw1h5RrGJIxIyfNYg6ylP9ekpOP93IQeY0DicuV6cDofucvQ8UhWKMGJwcgSg/aZBQB/Ewx/CZcSiKOTVBg8b4bFYYp4Sj3Qjhd4c9IosBpBo9TpwlWqb7hVKLOq5oSckA1SveUZ1cXzdLnbZWBF30RbC+DUgltU3Aasri/XdL4BBOW75pUJAQuj200y0/w/GFCH3DZ0FR6tB8R60GtiVwpc4X+xtN8P2+5WH1etowdMSQ5ECAFfwPb48GGbrN/0FbpQ/ZdjPnCr5p8ao9c0kTr57Ipk2kjZMabKEigXaRZ7BdAPtQFPFNchmsrR2TEexCRq60OybtbJfOqj1KnkuvyUHS3so6QUvYio6MnhpIKOPY02fYUos4AKbANiqPd69+kpl3u++do6xWIT0M9nOhND5sxDES9qN1SBp44wrCY26Nbt0Vgt0MIC3v5wGeMvrAx+3K/TET1UAvOLjGpw9wgAbyowmpKw==
    GRAFANA_ADMIN_USER: AgBlLjrJ87mAKWCi4n/u8P+Eeic6xsOxoM/5eu2wOHfywuAPvw5F0tl110gXvbOtgIEDXrJFIHCbmNjFutEviOKhUhPLaLaNILA2C/syHAh7wsZQ6uQaKOX6mFLuDGrBqxwKnnAWI9xImKf/ZG4J8E6DTT4Wo2byGJR74ew25eKtxv5uhzcF7QGlpOVnRwuXl8inqoZPfs/8ptBgQ4+bNEoadtvE9XoAZJsqKoKnu2Rq/Ia2ab4LVb7ckP5E0NTG1ZZNRCIS3QB3Kegv5jXeKOh7Z/gUOkxYCLhEdW3xCYqtt7fQmjrkbb8BQoej0CRE3Y7R/j10wUNE6146e0msrBvtwSfLvjvUEkkz6vzwLmz1sOy5iOD58kjleiYnCH+c5IHFz8BC39e6OzWOIllyRIBy4u+aUniHETvB1AqQGl6gj+xyGeypMObsCOKbobFcgJvhmN6cN1Wb60XXi1w3WFa0Sbg983RhMQsJ9JK2IxjlqtGJGKXFlvMsSrbPJOwJ7SYMC2Dh+5Ss3bfS9sK5s/nRA+n/aZ/SS/43v6wfg9/CDl+qd5fUKVOy3WPvcabZ2eV73i/GAYiV2C+Z3Z66GlBUXuhkZzCeYp4vtTi36fEZXMlJio8qrKSVDo2jg1KfMPathV4QqPbAwVJJN6Y31Zypx5cR2OFj7unid40Wps8Y62OltA0ihAhij5noFIXylvahiqWW+LU=
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
    type: Opaque
