---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mssql-secret
  namespace: default
spec:
  encryptedData:
    MSSQL_SA_PASSWORD: AgCtAnHlyLWxxhhU9sACoOYB7+E0yt7Dvp0y9GsMi+UQAG2WCUmldrKaVD1G5SJ3PUSaPIpFaZj0tzCabcNgYBdUs+QRQ8VpQoGC7+RRQrKu+o8o6Q0oGoKHWQM6TEkhcJ/r9UNvwQg1lxzHyeplNTgyHXSRXGSNCNaar3ljOFrg9qrltKOB6v+bbTojclznhltMiKwcKWSUceTxWtBXiVSwnvoshvBaMCWCQ9IYz8dLFMDRNLH7lS0iE1mV8jsY5gS9prJiIlPkCQoF6ne3XOsw+YZtoxeMcaWgtXhbmBQvx0TMxj8omxHlgmxxnP3VKEzz8a2czVBDAkO/uMJWLAX2ajMbMh+chFB7U8F6BxqRxijBEKyaLbQk5ZObADUmR2wBOqD63zV6wj4mtXojmUFnmMiiM5HUtXsr5jtach0hVPJoWzfhxqTAI9ZPl+F4c0r3Pp/yaHpO2vqOKofGHNTNCo58+u7dwxTdsLBvSG25H+FsqQCeY3VagRJUOF5ZEcDQIsToEIIo3Z3l6hlTX1CCPU3ZUJ+fU5n7rZcpOSGl+foXMtgeYWGpJ+WAXyuTont52nIwmlqZ7szEVOCM8LjtBmPBRI5RMPeWQcQw9fL8Jw2FVOhlHs7rpgTWYc8ySMQHpvMgjvEPXagaHec+bwNN0IbotJXn7uynpmgcLD0+rbWepGRBRAkRmpHtZSso+dqo1BFUoL7RFdnqHA==
  template:
    metadata:
      name: mssql-secret
      namespace: default
    type: Opaque
