---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slack-webhook-url
  namespace: monitoring
spec:
  encryptedData:
    SLACK_WEBHOOK_URL: AgAFmn6VNKYB+6VaTSc4XSHyw4izxt52gKvj8y5qdL4aCz800ZcZ0Clw7yPn74mWVG2ep9Ws3lQTRHmw1rLzza7DKlFqUjm5p9YTN/8KZ52GwXOyYbLafswo/oLt/h1h/Nxowr7NCZ2rVQ3ZVnJBPHtthLrTaPTFuDnSqE9L55RgcB9KkJ+vusZWK7uN6uflSmA54RcG4EKwugxwJNiVy36coa9BBfa3S3pmSvuftNv9j8UnRd3y0e3t7FzzqLNqtJlIBtJLzJR1AESHzRQ7sIcN23zpJ9Mo/DM12u7eJgJOVfeDWtTMBSjrRUXj2nkdgtTydDbWcyGyU3cqytk78YvaBRr6JbSFZ9T+EKnYZIqqva4M+xYGqwiBMURJE1PPDx/eRYvgU+RRnTGkc/2Y89mKeu0eUPm7qbxDaC5Y09W6VSb9AKYcItG2BIkXfjD24zU134zZQhPI1HEXwtEDm4pn6y2bNpGsVTgPZ0O+UH/a0cRF17IQHC+T+sKmL/GqzcugYRba4BVHwGAYb9+4l3kGQgJu5mIw0b0GyFYIW2eamKrY1AtzKPqiRiyqtcKBKQ6fHnD31CDJ/O4oRwMY5SWI8ucupgXabDmqM/bvvgrvBeUQ60ElTV+GNJPq15tm5J/q3PG5vy2VYPKoVnnqrTsz6WVaUlP00PchMvxx5GN+tFzRYLqts1M5c7/X7gJjsQjDdnNO9QRgu/CNlx+X1oXNWUzx7flcMA9P3eUcqNdB1CvA9gjbZ2TPriF8wXwaeB1ef36sdkH4PUdLbP6v9h6WAFnNn31ofqtGpw/r7771XO4b
  template:
    metadata:
      name: slack-webhook-url
      namespace: monitoring
    type: Opaque
