---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slack-webhook-url
  namespace: monitoring
spec:
  encryptedData:
    SLACK_WEBHOOK_URL: AgA3lDV2jTYzh1x5UmUnjJ6xYswivZg/FBs9XvsthYZDj25njNkaxhBuUBM9mKYUqW4ZRzwffg8J4RJ8yD3ujJ0xu6EoZmrlA+p2F2IRfKo7mpzW1i5VEitK2cMwK084maxCqSx5aIbgKJue6OwO/RDi/yiFp9V/nWQiqG7OqVp2TJLX67r3de/9jhAZSJfxT5D0Q1tTjGXTePOiSD4UhIeShivxdz9KrFUA+BNuxwmJHNz6i3YqonN/YTsYIadQe8nIZ/OFkvOibQg7vdOYnKgfin2+PFDBT0wpW02Ts/dnuIhkD7hK6JcSE5xLrF5zN/qV64VUoh0u8REYBtTFyKT7ulgyotxYF9vYoiaVUL/0lPiwZ7CW8xN6GPEHVCvbz3JeeZo91VVYQipISl0xla0aLnM/JbMCatYsNnqk1UbzXlbLCrYaDq/zePBasAJzA/9Am2soh6XeMJR+qM+HlNw6q8DGbj1MMCkgJbZ5qUnnb0Bncqsg4XygTq/IphGtgDefKTsjim1fPJQJ81xpi5Duc7HshLllH0F7OVRZVlj4kkHwSpzWunzlo0UJwEDV5u/uGIWjJ4egjWMo5m+tVARz+WeHmarKPUplTTRUMgSalwWQnpBIxFP8SoTvqbzWmVtlwrGiD0IUH30ZM5duyih5S/HnRLO10kaud4TLHCo6IjQPsRenDvGRM3nbBbBG2CuU9ebyiOTGY5nj/83DJMyRU+pvSSCuzaLVdvAbRCtuztZ+Ny/YOIUsNJoODpuiPJRmKIwtlQxY6wLPVs0w7Yzna73Pn4cPptYrpxpIIXfzjQMH
  template:
    metadata:
      name: slack-webhook-url
      namespace: monitoring
    type: Opaque
