---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slack-webhook-url
  namespace: monitoring
spec:
  encryptedData:
    SLACK_WEBHOOK_URL: AgA6ZVJeHJbR/d137I9MhWxTQokx0ZHuNNw+e2J1dxORS5x3ShY0HzdoZLfkxiXojZezgmlG5ZSs2acJq79WWWHkoD7dLqNnbWs5796Ga8opWneghovtYDj3ePfhqXTLCTtQgjaKql41jLEYK/MOLoFf6bgCVdAda+gZuR/sUpLNR1IihpQy231elJb7TLAE8bbEe6+a8FLqb7hPY/LYOeQFZYHe5bwEnOQKfHNdZmyVabTNzN8yw/zw28yogIa2hQ6OIzIKy8rTTjHJyRmQrxK/xLJtFhxUc2Wu9pkdewgwWzjnsYWb1epBblfMUg6BrKCFe7dXaqjRUanqCU3I1IBGApO50hEZjlPEFqfyQfCUQUM8a9YL4yb2pKZBzfdDIuVOt6bKPZEJJjz0AShXuQoHRXC0e49Hq796LSRbmW7kt0v/ufOP1IIGkvWlJcVjxMA+wrYDPg915mWifB5R4yvQSP1dYOCmFe2RurQAb+6PtkmQR0JMFGQelRRxJzlSFEdj8Iw8ojqbun65Bx5Ply7X0gDdirkPIRxdOW0USl6EaPvbMIL9PfKDNDm8oFcA+yyG8Y00YIgXg30eKYU3OTcFPOa6AuZGe5pcaSlqyyjCbtFse4+Bu8vL8iTmH3d7SrUymllB71uYsmRXhFz1aet/LVEYFxU5nbVqB4rZl0BrvfkXzvGGbmNmd2oH0BRj8b24RXGOBbzHtHm8qI8s2E282GhIWrwEE1VHvxjAt4YeRTL/JWk495z/P+VzWq3RXaSgZzEYnseEjMOhBn7ndxgEAPEy1TKCbp80Fs3iWrVDYMwB
  template:
    metadata:
      name: slack-webhook-url
      namespace: monitoring
    type: Opaque
