---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slack-webhook-url
  namespace: monitoring
spec:
  encryptedData:
    SLACK_WEBHOOK_URL: AgBzALCAQUzFCGr91uaBklvHCjRdy7MevLDyWu6fSEXzC514LuxtVU4TEwQ8iH4B93TeQD6JCvB/Wp+f2hbmdyhCMp/+WAPE4R+ts0ABNFix7pLucFdC1lgZSOSCeLdGRWB0RJZgaDLnpcsf/3kEVtysXk2QPnkITzIvaqegY/bL0+zgyV1qDUm5zoy0vSfBSV238xtiB6FGo1kSxYofcXuH85J6a+Ezj3qrX0hb8XWK/OvE38s5+dgtIwUupx9TugMqlFU8rha+RLlby/WF4prF2YtDF3behLiC8Ampemea48h2oIapv419Scxe8uHqQMnFVL5Fu6VHEw+NH807ok8/3TlxJqHY2Cyr3OyUlowOOepMluyzxa7WlY13CRYplEg32nhzHCzV2wSRJ3/6GaAMz+y+Rn/iKyEbIYWcza/1Euldp6PMIoRqetHJNsFzb9wT35DMA6IpNA6HzpZpt7rBHom4YdCghrqf8SRbL/knx/sSrTLMLIHiIWKim3YBUOFB2+5T9qOV91fLVa/RledHX5fAlAUIQSP+uktval9J7H86T56IMLhtsMvRXX5gkhTsgBBlHNRdxjs+70QVHj9gKuCswpMRvZ0PpD7R9xeQnkSWkmvQvQfEPLRF3ocstehXsKKlQ022KX0fQ0jmFmmWGqcnwZAj0dmN8BWJPKKMOZjePoUznc/Sz/Y7rQvS6jVNE1B8Kl8C4FHu896Qjxga28nBJOX19zK1IlCjo39UBOU8zlD7Xeh4AbqC8/P6DikXZAZIz3uNU0l30lLovjCehthLqnQG8FLJ3Q+NwbOiBGHt
  template:
    metadata:
      name: slack-webhook-url
      namespace: monitoring
    type: Opaque
