---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slack-webhook-url
  namespace: monitoring
spec:
  encryptedData:
    SLACK_WEBHOOK_URL: AgCUqXKD+1OEDn7XEqrkjHt7C/cLWZF5tC06KJwGLXiSGS9uPMgoGypXpTvnvtCT3HUNoILs1af7ejdD0TrioD0JOFfTAdq559Yai+dDjhU+oa3lE3moOKW15/07FGPd6keOUh/LthUBrFbAzD7+/itdY3UEJf7KWa2TkzvH5Z3qNUI7yjykjzphElm1GgIatApDeEyxowC0KPcPRS+1xQBunhYBexJDzuWNpkEj27ECMZcASVwAvUf0kyheYKfLqH7zzfAly+6b1mEi/BSiA8ahCCxBJCQno+NVnkka4EYmF9GkqYgP2bJoB68xZTZeuUhrGYGX3HeSX7E2+Hy3NYCgxHdh8TpmC5u/6azpaBsmtYxcWcYGugb7V99lr3eHi55PCn2B9wOgKKc0ONFOCZ/SlPfQUq1K86L+XD9X1zF1CtGXytbv2VF0Aoc407cLtF3f+M+JXakhIIjh4Ke6muqOEUC+s08Y13rjO3NkoxtWFR6LxqNOnOiHriW/6BhkbHymH+uFU+04PmWudlYssDp/RGda0etiUuHRWh1NIzdZYbFn7ENSxGOCSYoPhgN0Rz+mS8AtNJgugLa1Wif5EqZdVsK3+q7Cy2GzFMegfluwMGETxxw/Gw/XjgyT2FKNU3V19hTifsj5/pUYYETFLdoaXIvIsuGDXlJspao5HLxG14AR3qTY0lXu0HcdWT8mfBl/rxlKKHxH4idSf0SAVV+1SuC28FkRcvis1XN95uLJYMxSXMe4C03ffNTwrbr9yviNOtw3wV4cTvkAeWXAioScdKYHw/7gwHX6Ka+OOOz4AIzd
  template:
    metadata:
      name: slack-webhook-url
      namespace: monitoring
    type: Opaque
