apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # app
  - backend-deployment.yml
  - backend-svc.yml
  - backend-config.yml
  - frontend-deployment.yml
  - frontend-svc.yml
  - frontend-config.yml

  # database
  - mssql-deployment.yml
  - mssql-svc.yml
  - mssql-pvc.yml
  - mssql-bootstrap.yml

  # ingress
  - web-ingress.yml
  - api-ingress.yml

  # callmebot adapter (now included)
  - ../callmebot/callmebot.yml
